### ISSUE TITLE
let's provide possibility to return detected version and build

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina-appcenter#25]
I need functionality to remember and return separate values for version aka `2.24.0` and build `60060`.
```
14:49:30  2023-09-05 12:49:30 AppCenterManager [TestNG-test=iOS Handset Anthology QA-2-26] [INFO] Fetching Build ID (769) Version: 2.24.0 (60060)
14:49:30  2023-09-05 12:49:30 AppCenterManager [TestNG-test=iOS Handset Anthology QA-2-26] [INFO] Download URL For Build: https://appcenter-filemana....net/e1bee...e6de/Company%2B-...QA-2.24.0-60060.ipa?sv=token
```
as of now we generate and parse presign url which might be not so stable for all applications. That's why ability to preserve and return just version and build via appcenter manager looks ideal

**Comment by akamarouski** [comment]
Added getAppInfo method for getting information about app (direct link, version, build). This method thread safe and cache results.

**Comment by akamarouski** [comment]
Changes should be duplicated to the 1.2.6 release

**Comment by akamarouski** [comment]
Added getAppInfo method that allows to get direct link, version and build version of application
